branch-defaults:
  AWS:
    environment: secapp-env
    group_suffix: null
global:
  application_name: secapp
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: us-west-2
  profile: eb-cli
  sc: git
