branch-defaults:
  aws_puma:
    environment: secapppuma-env
    group_suffix: null
global:
  application_name: secapp_puma
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
